server.port=8761

# Disable the client side registration and fetching
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable the service registry feature that is causing the crash
spring.cloud.service-registry.auto-registration.enabled=false